---
title: "01_start"
author: "Ziwei Crystal Zang"
date: "3/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())

for (pkg in c("tidyverse", "readr", "dplyr", "countrycode")) {library(pkg, character.only = TRUE)}

```


```{r}
coronavirus_summary <- read_csv("/Users/czang/Documents/2021Spring/R/biost2094_project/data/coronavirus_summary.csv")
coronavirus_summary$iso_code <- countrycode(coronavirus_summary$country, 'country.name','iso3c')
coronavirus_summary <- select(coronavirus_summary, -country)

vaccine <- read_csv("/Users/czang/Documents/2021Spring/R/biost2094_project/data/vaccinations.csv")
name_list <- c("OWID_ENG", "OWID_NIR", "OWID_SCT", "OWID_WLS")
vaccine$iso_code <- with(vaccine, replace(iso_code, iso_code %in% name_list, "GBR"))

combine <- merge(vaccine, coronavirus_summary, by="iso_code", all.x=T)
```

# Inconsistent country names between two datasets 
Countries that failed to merge: Guernsey, Jersey, Northern Cyprus, and Saint Helena
```{r}
country_name_vaccine <- vaccine%>%
  distinct(iso_code, .keep_all=T )%>%
  select(country, iso_code)%>%
  rename("country_v" = "country", "iso_code_v" = "iso_code")%>%
  mutate(vaccine_data = T)

#edit country name in the covid data
country_name_covid <- coronavirus_summary%>%
  distinct(iso_code, .keep_all=T )%>%
  select(country, iso_code)%>%
  rename("country_covid" = "country", "iso_code_covid" = "iso_code")%>%
  mutate(covid_data = T)
#merge two data sets

country_name <- merge(country_name_vaccine,country_name_covid, by.x="iso_code_v",by.y = "iso_code_covid", all.x=T)

country_name_na <- country_name%>%
  filter(is.na(covid_data))
```

```{r}
combine <- merge(coronavirus_summary,vaccine, by="iso_code", all=T)
```

