---
title: "03_clean_na"
author: "Ziwei Crystal Zang"
date: "4/10/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Finalized code
```{r}
for (pkg in c("tidyverse", "readr", "dplyr", "countrycode", "zoo")) {library(pkg, character.only = TRUE)}

vaccine <- read_csv("/Users/czang/Documents/2021Spring/R/biost2094_project/data/vaccinations.csv")
name_list <- c("OWID_ENG", "OWID_NIR", "OWID_SCT", "OWID_WLS")
vaccine$iso_code <- with(vaccine, replace(iso_code, iso_code %in% name_list, "GBR"))
coronavirus_summary <- read_csv("/Users/czang/Documents/2021Spring/R/biost2094_project/data/coronavirus_summary.csv")

coronavirus_summary$iso_code <- countrycode(coronavirus_summary$country, 'country.name','iso3c')
covronavirus <- coronavirus_summary %>% select(-country)
combine <- merge(vaccine, covronavirus, by="iso_code", all.x=T)

combine_extra <- combine%>%
  select(country, date,people_vaccinated)

combine$date <- as.Date(combine$date,"%m/%d/%Y")

# combine2 <-combine %>%
#   select(country,date, population, daily_vaccinations,continent)%>%
#   group_by(country)%>%
#   arrange(date)%>%
#   mutate(daily_vaccinations = if_else(is.na(daily_vaccinations ), 0, daily_vaccinations))%>%
#   group_by(country)%>%
#   mutate(sum = cumsum(daily_vaccinations))


#countries that doesn't have any people_vaccinated
countries_0 <- combine%>%
  group_by(country)%>%
  summarize(total_vaccinations = max(sum, na.rm=T))%>%
  filter(total_vaccinations==0)%>%
  pull(country)

'%notin%' <- Negate('%in%')
combine_new <- combine%>%
  select(country, date, daily_vaccinations,population,continent)%>%
  filter(country %notin% countries_0)
#if values are 0, fill in as na
combine_new$daily_vaccinations <-na_if(combine_new$daily_vaccinations,0)

country_info <- combine_new%>%
  select(country, population,continent)%>%
  distinct()

combine_new <- combine_new%>%
  select(-population, -continent)

combine_new_spread <- combine_new%>%
  spread(key = date, value =daily_vaccinations)%>%
  column_to_rownames("country")

s <- apply(combine_new_spread, 2, function(x) na.fill(x, list(0, "extend", "extend")))
s <- as.data.frame(s)
s <- s%>%
  rownames_to_column("country")

vaccine_final <- gather(s, key = "date", value = "daily_vaccinations",-country)
vaccine_final <- left_join(vaccine_final, country_info, by = "country")
vaccine_final <- vaccine_final%>%
  group_by(country)%>%
  mutate(cumsum_total_vaccination = cumsum(daily_vaccinations))
  

vaccine_final$date <- as.Date(vaccine_final$date,"%Y-%m-%d")

vaccine_final_all <- merge(vaccine_final, combine_extra, by = c("country", "date"))

write.csv(vaccine_final_all, "data/clean_vaccine.csv", row.names = F)
#united states
ggplot(data = filter(vaccine_final, country=="United States"), aes(x = date, y = total_vaccine)) + 
  geom_line()  +
  geom_point(size = 0.5)+
  aes(colour = country) + 
  theme(legend.position = "right") +
  labs(title = "")

#color by country
ggplot(data = vaccine_final, aes(x = date, y = total_vaccine)) + geom_line()  + 
  aes(colour = country) + 
  theme(legend.position = "right") + labs(title = "")
```

```{r}
#countries that doesn't have any people_vaccinated
countries_0 <- combine%>%
  group_by(country)%>%
  summarize(max = max(people_vaccinated, na.rm=T))%>%
  filter(max==0)%>%
  pull(country)

'%notin%' <- Negate('%in%')
combine_new <- combine%>%
  select(country, date, daily_vaccinations,population,continent)%>%
  filter(country %notin% countries_0)
#if values are 0, fill in as na
combine_new$daily_vaccinations <-na_if(combine_new$daily_vaccinations,0)

country_info <- combine_new%>%
  select(country, population,continent)%>%
  distinct()

combine_new <- combine_new%>%
  select(-population, -continent)

combine_new_spread <- combine_new%>%
  spread(key = date, value =daily_vaccinations)%>%
  column_to_rownames("country")

s <- apply(combine_new_spread, 2, function(x) na.fill(x, list(0, "extend", "extend")))
s <- as.data.frame(s)
s <- s%>%
  rownames_to_column("country")

vaccine_final <- gather(s, key = "date", value = "daily_people_vaccinated",-country)
vaccine_final <- left_join(vaccine_final, country_info, by = "country")
vaccine_final <- vaccine_final%>%
  group_by(country)%>%
  mutate(total_vaccine = cumsum(daily_people_vaccinated))
  

vaccine_final$date <- as.Date(vaccine_final$date,"%Y-%m-%d")


#united states
ggplot(data = filter(vaccine_final, country=="United States"), aes(x = date, y = total_vaccine)) + 
  geom_line()  +
  geom_point(size = 0.5)+
  aes(colour = country) + 
  theme(legend.position = "right") +
  labs(title = "")

#color by country
ggplot(data = vaccine_final, aes(x = date, y = total_vaccine)) + geom_line()  + 
  aes(colour = country) + 
  theme(legend.position = "right") + labs(title = "")
```

# Experimental code
```{r}
for (pkg in c("tidyverse", "readr", "dplyr", "countrycode")) {library(pkg, character.only = TRUE)}

vaccine <- read_csv("/Users/czang/Documents/2021Spring/R/biost2094_project/data/vaccinations.csv")
name_list <- c("OWID_ENG", "OWID_NIR", "OWID_SCT", "OWID_WLS")
vaccine$iso_code <- with(vaccine, replace(iso_code, iso_code %in% name_list, "GBR"))
coronavirus_summary <- read_csv("/Users/czang/Documents/2021Spring/R/biost2094_project/data/coronavirus_summary.csv")

coronavirus_summary$iso_code <- countrycode(coronavirus_summary$country, 'country.name','iso3c')
covronavirus <- coronavirus_summary %>% select(-country)
combine <- merge(vaccine, covronavirus, by="iso_code", all.x=T)
head(combine)

combine$date <- as.Date(combine$date,"%m/%d/%Y")
combine_new <-combine %>%
  select(country,date,total_vaccinations,people_fully_vaccinated,people_vaccinated,total_vaccinations_per_hundred, population, daily_vaccinations)%>%
  group_by(country)%>%
  arrange(date)%>%
  mutate(daily_vaccinations = if_else(is.na(daily_vaccinations ), 0, daily_vaccinations))%>%
  group_by(country)%>%
  mutate(sum = cumsum(daily_vaccinations))%>%
  select(country,date,total_vaccinations,people_fully_vaccinated,people_vaccinated,daily_vaccinations, sum)

#count non NA values for each country
check <- combine_new%>%
  select(country, date, total_vaccinations)%>%
  mutate(is_na = is.na(total_vaccinations))%>%
  group_by(country)%>%
  summarize(sum(is_na))
  
#compare the original total count and cumulative sum daily count
combine_new_summarize <- combine_new%>%
  group_by(country)%>%
  summarize(total_doses=max(total_vaccinations,na.rm=T),
            total_doses_na = sum(is.na(total_vaccinations)),
            total_doses_imputed = max(sum, na.rm=T),
             total_doses_imputed_na = sum(is.na(sum)),
            people_vaccination = max(people_vaccinated, na.rm=T),
                 people_vaccination_na = sum(is.na(people_vaccinated)),
            total_vaccination_fully = max(people_fully_vaccinated,na.rm=T),
                  total_vaccination_fully_na = sum(is.na(people_fully_vaccinated)))

# combine_new_fix <- combine_new%>%
#   select(country, date,people_vaccinated)%>%
#   group_by(country)%>%
#   mutate(start_date = min(date))

# n = length(unique(combine_new$country))
country_name <- unique(combine_new$country)
# startdate = "2020-12-13"
# enddate = "2021-03-22"
# matrix <- matrix(data= NA,nrow =n, ncol = 99)
# for (c in country_name){
# }

#countries that doesn't have any people_vaccinated
countries_0 <- combine_new%>%
  group_by(country)%>%
  summarize(total_vaccinations = max(sum, na.rm=T))%>%
  filter(total_vaccinations==0)%>%
  pull(country)

'%notin%' <- Negate('%in%')
df <- combine_new%>%
  select(country, date,total_vaccinations)%>%
  filter(country %notin% countries_0)
df$total_vaccinations <-na_if(df$total_vaccinations,0)

# Azerbaijan <- df%>%
#   filter(country =="Azerbaijan")%>%
#   select(date,people_vaccinated)

df <- df%>%
  spread(key = date, value =total_vaccinations)%>%
  column_to_rownames("country")

# Azerbaijan <- as.data.frame(t(df["Azerbaijan",]))
# Azerbaijan_z <- as.data.frame(na.fill(Azerbaijan, list(0, NA, "extend")))
#Azerbaijan_c <- cbind(Azerbaijan,Azerbaijan_z)

s <- apply(df, 2, function(x) na.fill(x, list(0, "extend", "extend")))

Azerbaijan2 <- s["Azerbaijan",]
Azerbaijan2_z <- as.data.frame(na.fill(Azerbaijan2, list(0, NA, "extend")))



library(zoo)
z <- c(NA,NA,NA,NA,NA,NA,NA,NA, 1, NA,10,NA,NA,40, 50, NA)
na.fill(z, list(0, NA, "extend"))
na.fill(z, list(0, 'extend', "extend"))
class(z)
z <- zoo(z)
z
z_c <- na.fill(z, "extend")
z_c
na.fill(z, c("extend", NA))
na.fill(z, -(1:3))
na.fill(z, list(0, NA, "extend"))

```

