---
title: "01_start"
author: "Ziwei Crystal Zang"
date: "3/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
```

```{r}
coronavirus_daily <- read_csv("data/coronavirus_daily.csv")
coronavirus_summary <- read_csv("data/coronavirus_summary.csv")
vaccine <- read_csv("data/vaccinations.csv")
```


```{r}
View(coronavirus_daily)
View(coronavirus_summary)
View(vaccine)
```

# Inconsistent country names between two datasets 
```{r}
#edit country name in the vaccine data
country_name_vaccine <- as.data.frame(unique(vaccine$country))
country_name_vaccine <- cbind(country_name_vaccine, "vaccine")
colnames(country_name_vaccine) <- c("country", "vaccine_data")

#edit country name in the covid data
country_name_covid <- unique(coronavirus_summary$country)
country_name_covid <- cbind(country_name_covid, "covid")
colnames(country_name_covid) <- c("country", "covid_data")

#merge two data sets
country_name <- merge(country_name_vaccine,country_name_covid, by="country", all=T)

country_name_na <- country_name%>%
  filter(is.na(vaccine_data) | is.na(covid_data) )
View(country_name_na)
```

